let container = document.createElement('div')
let header = document.createElement('header')
let header__div = document.createElement('div')
let haeder__top__left = document.createElement('div')
let haeder__top__left__nav = document.createElement('nav')
let haeder__top__ul = document.createElement('ul')
let liOne = document.createElement('li')
let liTwo = document.createElement('li')
let liThree = document.createElement('li')
let aOne = document.createElement('a')
let aTwo = document.createElement('a')
let aThree = document.createElement('a')
let haeder__top__right = document.createElement('div')
let haeder__top__right__nav = document.createElement('nav')
let haeder__top__ulONe = document.createElement('ul')
let liFour = document.createElement('li')
let liFive = document.createElement('li')
let liSix = document.createElement('li')
let aFour = document.createElement('a')
let aFive = document.createElement('a')
let aSix = document.createElement('a')
let phone = document.createElement('div')
let imgOne = document.createElement('img')
let liSeven = document.createElement('li')
let aSeven = document.createElement('a')
let headerClass = document.createElement('div')
let header__logo = document.createElement('div')
let h1 = document.createElement('h1')
let aEight = document.createElement('a')
let field__section = document.createElement('div')
let btnOne = document.createElement('button')
let imgTwo = document.createElement('img')
let form = document.createElement('form')
let input = document.createElement('input')
let field__section__btn = document.createElement('button')
let categories = document.createElement('div')
let status = document.createElement('div')
let profile = document.createElement('div')
let sprite = document.createElement('div')
let heart = document.createElement('div')
let shop = document.createElement('div')
let statusImg = document.createElement('img')
let profileImg = document.createElement('img')
let spriteImg = document.createElement('img')
let heartImg = document.createElement('img')
let shopImg = document.createElement('img')
let statusPar = document.createElement('p')
let profilePar = document.createElement('p')
let spritePar = document.createElement('p')
let heartPar = document.createElement('p')
let shopPar = document.createElement('p')


container.append(header)
header.append(haeder__top__left, haeder__top__right)
haeder__top__left.append(haeder__top__left__nav)
haeder__top__left__nav.append(haeder__top__ul)
haeder__top__ul.append(liOne, liTwo, liThree)
liOne.append(aOne)
liTwo.append(aTwo)
liThree.append(aThree)

aOne.innerHTML = 'Магазины'
